csi:
  plugin:
    name: fuse-csi
    # Attempt to restore FUSE mounts. Doesn't work.
    restoreMounts: true

  registrar:
    image: quay.io/k8scsi/csi-node-driver-registrar:v2.1.0

  v3ioFuse:
      image:
        repository: gcr.io/iguazio/v3io-fuse
        tag: 3.6.0-b8495.20220511182230
        pullPolicy: IfNotPresent
# Override the default app name using nameOverride
# nameOverride: some-other-name

