apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.csi.plugin.name }}
  namespace: default
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
